### ISSUE TITLE
Lora files missing

### ISSUE THREAD

**Issue by DrUmranAli** [Avaray/lora-keywords-finder#11]
Using the latest commit of SD Forge, everything appears to be installed properly however none of the Lora files show up; they are in the Lora folder (not in any sub folders) from civitai, but even on refreshing; nothing shows up?

**Comment by Avaray** [comment]
What are extensions of Lora files? (currently only .pt and .safetensors are listed)  
How do you run your ForgeUI? (did you install it from official installer? are you using stability matrix or something similar? using docker image?)  
Need some more details

**Comment by DrUmranAli** [comment]
.safetensors files
Using the official installer, fully up to date, the extension appears fine and on clicking the refresh it refreshes(processing) but nothing shows up.

Lora folder is in webui/models/Lora

**Comment by Avaray** [comment]
I know this is silly question, but did you open the list (it's a dropdown menu)?  

Button for refreshing the list is only to refresh the list if needed (when you added loras after launching Forge, because extension is not "sniffing" for changes in Lora directory).   
List of loras is generated at the launch time of Forge and the first position will be always empty (that prevents extension for fetching data at the launch time).

**Comment by DrUmranAli** [comment]
Yes tried that, the list is empty.

**Comment by Avaray** [comment]
What is your Operating System?
